format = """
[┏━](#5a00e2)[](#5a00e2)\
$os\
[](bg:#7c00e0 fg:#5a00e2)\
$username\
[](bg:#9e00dd fg:#7c00e0)\
$directory\
[](fg:#9e00dd bg:#c100da)\
$git_branch\
$git_status\
[](fg:#c100da bg:#e300d8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#e300d8 bg:#fb00e2)\
$docker_context\
[](fg:#fb00e2 bg:#fe00e6)\
$time\
[ ](fg:#fe00e6)
[┃](#5a00e2)
[┗━━━](#5a00e2)\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#7c00e0 bold"
style_root = "bg:#7c00e0 bold	"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#5a00e2 bold"
disabled = false # Disabled by default
format = '[ ]($style)'

[directory]
style = "bg:#9e00dd bold"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#fb00e2 bold"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#c100da bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#c100da bold"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#e300d8 bold"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#fe00e6 black bold"
format = '[ $time ]($style)'
